# SonarQube Cloud
sonar.organization=chabelly-lbetancourt
sonar.projectKey=chabelly-lbetancourt_oneleft-frontend
sonar.projectName=OneLeft · Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.coverage.exclusions=src/main.ts,src/app/app.config.ts,src/app/app.routes.ts
sonar.javascript.lcov.reportPaths=coverage/oneleft/lcov.info
sonar.sourceEncoding=UTF-8
