import { ADMIN, ANA, API_URL, expect, signIn, test, uniqueTitle } from './support/fixtures';

test('a shared link previews the plan, opens it without a session and brings the guest back after signing in', async ({
  openPage,
  publishPlan,
  request,
  t,
}) => {
  const plan = await publishPlan(ANA, uniqueTitle('E2E share'));
  const link = `${API_URL}/share/plans/${plan.id}`;

  // What messaging apps read: Open Graph tags generated by the server
  const preview = await (await request.get(link)).text();
  expect(preview).toContain(`<meta property="og:title" content="${plan.title}">`);
  expect(preview).toContain('og:image');

  // Someone without an account opens the link: the plan, without names
  const guest = await openPage();
  await guest.goto(link);
  await guest.waitForURL(`**/plans/${plan.id}`);
  await expect(guest.locator('.plan-card')).toContainText(plan.title);
  await expect(guest.locator('.plan-card')).not.toContainText('Ana');
  await expect(guest.locator('.share-button')).toBeVisible();

  // Joining asks to sign in and comes back to the plan
  await guest.locator('.guest-join button').click();
  await signIn(guest, ADMIN);
  await guest.waitForURL(`**/plans/${plan.id}`);
  await guest.locator('.join-button button').click();
  await expect(guest.locator('.joined-message')).toContainText(t('plan.justJoined'));
});
